name: neocities
description: Neocities rest api client and cli interface
version: 0.0.1
repository: https://github.com/natebot13/neocities

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: 
  json_annotation: ^4.9.0
  intl:
  async:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner:
  json_serializable:
