name: neocities
description: Neocities api client
version: 1.0.0
repository: https://github.com/natebot13/neocities_dart

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  quiver: ^3.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
